export const allCurrencies = [
  { symbol: 'USD', label: 'United States (USD)' },
  { symbol: 'CAD', label: 'Canadian Dollar (CAD)' },
  { symbol: 'EUR', label: 'Euro (EUR)' },
  { symbol: 'GBP', label: 'British Pound (GBP)' },
  { symbol: 'AFN', label: 'Afghan Afghani (AFN)' },
  { symbol: 'ALL', label: 'Albanian Lek (ALL)' },
  { symbol: 'DZD', label: 'Algerian Dinar (DZD)' },
  { symbol: 'AOA', label: 'Angolan Kwanza (AOA)' },
  { symbol: 'ARS', label: 'Argentine Peso (ARS)' },
  { symbol: 'AMD', label: 'Armenian Dram (AMD)' },
  { symbol: 'AWG', label: 'Aruban Florin (AWG)' },
  { symbol: 'AUD', label: 'Australian Dollar (AUD)' },
  { symbol: 'BBD', label: 'Barbadian Dollar (BBD)' },
  { symbol: 'AZN', label: 'Azerbaijani Manat (AZN)' },
  { symbol: 'BDT', label: 'Bangladeshi Taka (BDT)' },
  { symbol: 'BSD', label: 'Bahamian Dollar (BSD)' },
  { symbol: 'BHD', label: 'Bahraini Dinar (BHD)' },
  { symbol: 'BIF', label: 'Burundian Franc (BIF)' },
  { symbol: 'BYN', label: 'Belarusian Ruble (BYN)' },
  { symbol: 'BYR', label: 'Belarusian Ruble (BYR)' },
  { symbol: 'BZD', label: 'Belize Dollar (BZD)' },
  { symbol: 'BMD', label: 'Bermudan Dollar (BMD)' },
  { symbol: 'BTN', label: 'Bhutanese Ngultrum (BTN)' },
  { symbol: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark (BAM)' },
  { symbol: 'BRL', label: 'Brazilian Real (BRL)' },
  { symbol: 'BOB', label: 'Bolivian Boliviano (BOB)' },
  { symbol: 'BWP', label: 'Botswanan Pula (BWP)' },
  { symbol: 'BND', label: 'Brunei Dollar (BND)' },
  { symbol: 'BGN', label: 'Bulgarian Lev (BGN)' },
  { symbol: 'MMK', label: 'Myanmar Kyat (MMK)' },
  { symbol: 'KHR', label: 'Cambodian Riel (KHR)' },
  { symbol: 'CVE', label: 'Cape Verdean Escudo (CVE)' },
  { symbol: 'KYD', label: 'Cayman Islands Dollar (KYD)' },
  { symbol: 'XAF', label: 'Central African CFA Franc (XAF)' },
  { symbol: 'CLP', label: 'Chilean Peso (CLP)' },
  { symbol: 'CNY', label: 'Chinese Yuan (CNY)' },
  { symbol: 'COP', label: 'Colombian Peso (COP)' },
  { symbol: 'KMF', label: 'Comorian Franc (KMF)' },
  { symbol: 'CDF', label: 'Congolese Franc (CDF)' },
  { symbol: 'CRC', label: 'Costa Rican Colón (CRC)' },
  { symbol: 'HRK', label: 'Croatian Kuna (HRK)' },
  { symbol: 'CZK', label: 'Czech Koruna (CZK)' },
  { symbol: 'DKK', label: 'Danish Krone (DKK)' },
  { symbol: 'DJF', label: 'Djiboutian Franc (DJF)' },
  { symbol: 'DOP', label: 'Dominican Peso (DOP)' },
  { symbol: 'XCD', label: 'East Caribbean Dollar (XCD)' },
  { symbol: 'EGP', label: 'Egyptian Pound (EGP)' },
  { symbol: 'ETB', label: 'Ethiopian Birr (ETB)' },
  { symbol: 'FKP', label: 'Falkland Islands Pound (FKP)' },
  { symbol: 'XPF', label: 'CFP Franc (XPF)' },
  { symbol: 'FJD', label: 'Fijian Dollar (FJD)' },
  { symbol: 'GIP', label: 'Gibraltar Pound (GIP)' },
  { symbol: 'GMD', label: 'Gambian Dalasi (GMD)' },
  { symbol: 'GHS', label: 'Ghanaian Cedi (GHS)' },
  { symbol: 'GTQ', label: 'Guatemalan Quetzal (GTQ)' },
  { symbol: 'GYD', label: 'Guyanaese Dollar (GYD)' },
  { symbol: 'GEL', label: 'Georgian Lari (GEL)' },
  { symbol: 'GNF', label: 'Guinean Franc (GNF)' },
  { symbol: 'HTG', label: 'Haitian Gourde (HTG)' },
  { symbol: 'HNL', label: 'Honduran Lempira (HNL)' },
  { symbol: 'HKD', label: 'Hong Kong Dollar (HKD)' },
  { symbol: 'HUF', label: 'Hungarian Forint (HUF)' },
  { symbol: 'ISK', label: 'Icelandic Króna (ISK)' },
  { symbol: 'INR', label: 'Indian Rupee (INR)' },
  { symbol: 'IDR', label: 'Indonesian Rupiah (IDR)' },
  { symbol: 'ILS', label: 'Israeli New Shekel (ILS)' },
  { symbol: 'IRR', label: 'Iranian Rial (IRR)' },
  { symbol: 'IQD', label: 'Iraqi Dinar (IQD)' },
  { symbol: 'JMD', label: 'Jamaican Dollar (JMD)' },
  { symbol: 'JPY', label: 'Japanese Yen (JPY)' },
  { symbol: 'JEP', label: 'Jersey Pound (JEP)' },
  { symbol: 'JOD', label: 'Jordanian Dinar (JOD)' },
  { symbol: 'KZT', label: 'Kazakhstani Tenge (KZT)' },
  { symbol: 'KES', label: 'Kenyan Shilling (KES)' },
  { symbol: 'KWD', label: 'Kuwaiti Dinar (KWD)' },
  { symbol: 'KGS', label: 'Kyrgystani Som (KGS)' },
  { symbol: 'LAK', label: 'Laotian Kip (LAK)' },
  { symbol: 'LVL', label: 'Latvian Lats (LVL)' },
  { symbol: 'LBP', label: 'Lebanese Pound (LBP)' },
  { symbol: 'LSL', label: 'Lesotho Loti (LSL)' },
  { symbol: 'LRD', label: 'Liberian Dollar (LRD)' },
  { symbol: 'LYD', label: 'Libyan Dinar (LYD)' },
  { symbol: 'MGA', label: 'Malagasy Ariary (MGA)' },
  { symbol: 'MKD', label: 'Macedonian Denar (MKD)' },
  { symbol: 'MOP', label: 'Macanese Pataca (MOP)' },
  { symbol: 'MWK', label: 'Malawian Kwacha (MWK)' },
  { symbol: 'MVR', label: 'Maldivian Rufiyaa (MVR)' },
  { symbol: 'MXN', label: 'Mexican Peso (MXN)' },
  { symbol: 'MYR', label: 'Malaysian Ringgit (MYR)' },
  { symbol: 'MUR', label: 'Mauritian Rupee (MUR)' },
  { symbol: 'MDL', label: 'Moldovan Leu (MDL)' },
  { symbol: 'MAD', label: 'Moroccan Dirham (MAD)' },
  { symbol: 'MNT', label: 'Mongolian Tugrik (MNT)' },
  { symbol: 'MZN', label: 'Mozambican Metical (MZN)' },
  { symbol: 'NAD', label: 'Namibian Dollar (NAD)' },
  { symbol: 'NPR', label: 'Nepalese Rupee (NPR)' },
  { symbol: 'ANG', label: 'Netherlands Antillean Guilder (ANG)' },
  { symbol: 'NZD', label: 'New Zealand Dollar (NZD)' },
  { symbol: 'NIO', label: 'Nicaraguan Córdoba (NIO)' },
  { symbol: 'NGN', label: 'Nigerian Naira (NGN)' },
  { symbol: 'NOK', label: 'Norwegian Krone (NOK)' },
  { symbol: 'OMR', label: 'Omani Rial (OMR)' },
  { symbol: 'PAB', label: 'Panamanian Balboa (PAB)' },
  { symbol: 'PKR', label: 'Pakistani Rupee (PKR)' },
  { symbol: 'PGK', label: 'Papua New Guinean Kina (PGK)' },
  { symbol: 'PYG', label: 'Paraguayan Guarani (PYG)' },
  { symbol: 'PEN', label: 'Peruvian Sol (PEN)' },
  { symbol: 'PHP', label: 'Philippine Piso (PHP)' },
  { symbol: 'PLN', label: 'Polish Zloty (PLN)' },
  { symbol: 'QAR', label: 'Qatari Rial (QAR)' },
  { symbol: 'RON', label: 'Romanian Leu (RON)' },
  { symbol: 'RUB', label: 'Russian Ruble (RUB)' },
  { symbol: 'RWF', label: 'Rwandan Franc (RWF)' },
  { symbol: 'WST', label: 'Samoan Tala (WST)' },
  { symbol: 'SHP', label: 'St. Helena Pound (SHP)' },
  { symbol: 'SAR', label: 'Saudi Riyal (SAR)' },
  { symbol: 'STD', label: 'São Tomé &amp; Príncipe Dobra (STD)' },
  { symbol: 'RSD', label: 'Serbian Dinar (RSD)' },
  { symbol: 'SCR', label: 'Seychellois Rupee (SCR)' },
  { symbol: 'SLL', label: 'Sierra Leonean Leone (SLL)' },
  { symbol: 'SGD', label: 'Singapore Dollar (SGD)' },
  { symbol: 'SDG', label: 'Sudanese Pound (SDG)' },
  { symbol: 'SYP', label: 'Syrian Pound (SYP)' },
  { symbol: 'ZAR', label: 'South African Rand (ZAR)' },
  { symbol: 'KRW', label: 'South Korean Won (KRW)' },
  { symbol: 'SSP', label: 'South Sudanese Pound (SSP)' },
  { symbol: 'SBD', label: 'Solomon Islands Dollar (SBD)' },
  { symbol: 'LKR', label: 'Sri Lankan Rupee (LKR)' },
  { symbol: 'SRD', label: 'Surinamese Dollar (SRD)' },
  { symbol: 'SZL', label: 'Swazi Lilangeni (SZL)' },
  { symbol: 'SEK', label: 'Swedish Krona (SEK)' },
  { symbol: 'CHF', label: 'Swiss Franc (CHF)' },
  { symbol: 'TWD', label: 'New Taiwan Dollar (TWD)' },
  { symbol: 'THB', label: 'Thai Baht (THB)' },
  { symbol: 'TJS', label: 'Tajikistani Somoni (TJS)' },
  { symbol: 'TZS', label: 'Tanzanian Shilling (TZS)' },
  { symbol: 'TOP', label: 'Tongan Paʻanga (TOP)' },
  { symbol: 'TTD', label: 'Trinidad &amp; Tobago Dollar (TTD)' },
  { symbol: 'TND', label: 'Tunisian Dinar (TND)' },
  { symbol: 'TRY', label: 'Turkish Lira (TRY)' },
  { symbol: 'TMT', label: 'Turkmenistani Manat (TMT)' },
  { symbol: 'UGX', label: 'Ugandan Shilling (UGX)' },
  { symbol: 'UAH', label: 'Ukrainian Hryvnia (UAH)' },
  { symbol: 'AED', label: 'United Arab Emirates Dirham (AED)' },
  { symbol: 'UYU', label: 'Uruguayan Peso (UYU)' },
  { symbol: 'UZS', label: 'Uzbekistani Som (UZS)' },
  { symbol: 'VUV', label: 'Vanuatu Vatu (VUV)' },
  { symbol: 'VEF', label: 'Venezuelan Bolívar (VEF)' },
  { symbol: 'VND', label: 'Vietnamese Dong (VND)' },
  { symbol: 'XOF', label: 'West African CFA Franc (XOF)' },
  { symbol: 'YER', label: 'Yemeni Rial (YER)' },
  { symbol: 'ZMW', label: 'Zambian Kwacha (ZMW)' }
];
